# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\x18\n\x07Request\x12\r\n\x05input\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06output\x18\x02 \x01(\t2=\n\x0b\x44\x65moService\x12.\n\x07Process\x12\x0f.common.Request\x1a\x10.common.Response\"\x00\x42\x19Z\x17grpc_demo/proto/gen;genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027grpc_demo/proto/gen;gen'
  _globals['_REQUEST']._serialized_start=24
  _globals['_REQUEST']._serialized_end=48
  _globals['_RESPONSE']._serialized_start=50
  _globals['_RESPONSE']._serialized_end=76
  _globals['_DEMOSERVICE']._serialized_start=78
  _globals['_DEMOSERVICE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
